export const SET_APP = 'SET_APP';
export const REQUEST_LOGIN_USER_WITH_FB = 'REQUEST_LOGIN_USER_WITH_FB';
export const REQUEST_CREATE_USER_WITH_FB = 'REQUEST_CREATE_USER_WITH_FB';
export const REQUEST_LOGOUT_USER_WITH_FB = 'REQUEST_LOGOUT_USER_WITH_FB';
export const REQUEST_GET_ALL_PRODUCTS_WITH_FB = 'REQUEST_GET_ALL_PRODUCTS_WITH_FB';

export const REQUEST_ADD_PRODUCT_FB = 'REQUEST_ADD_PRODUCT_FB';
export const REQUEST_GET_PRODUCTS_FB = 'REQUEST_GET_PRODUCTS_FB';
export const FIREBASE_PRODUCTS_LISTENER = 'FIREBASE_PRODUCTS_LISTENER';
